In [18]:
import pandas as pd

In [19]:
#csv into dataframe
df1 = pd.read_csv('daily_food_nutrition_dataset.csv')
df1

,Date,User_ID,Food_Item,Category,Calories (kcal),Protein (g),Carbohydrates (g),Fat (g),Fiber (g),Sugars (g),Sodium (mg),Cholesterol (mg),Meal_Type,Water_Intake (ml)
0,2024-09-11,496,Eggs,Meat,173,42.4,83.7,1.5,1.5,12.7,752,125,Lunch,478
1,2024-12-17,201,Apple,Fruits,66,39.2,13.8,3.2,2.6,12.2,680,97,Lunch,466
2,2024-06-09,776,Chicken Breast,Meat,226,27.1,79.1,25.8,3.2,44.7,295,157,Breakfast,635
3,2024-08-27,112,Banana,Fruits,116,43.4,47.1,16.1,6.5,44.1,307,13,Snack,379
4,2024-07-28,622,Banana,Fruits,500,33.9,75.8,47.0,7.8,19.4,358,148,Lunch,471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024-09-18,455,Salmon,Meat,346,29.8,55.6,4.6,1.7,0.5,976,87,Breakfast,793
9996,2024-12-13,913,Grapes,Fruits,174,22.9,54.9,32.1,2.5,5.9,255,56,Lunch,665
9997,2024-01-31,943,Strawberry,Fruits,63,36.5,23.8,21.6,0.8,48.9,757,63,Snack,876
9998,2024-09-28,571,Spinach,Vegetables,564,26.2,58.9,11.9,3.3,43.0,482,33,Breakfast,319
9999,2024-09-07,33,Banana,Fruits,442,20.9,27.3,29.6,9.9,30.9,919,22,Dinner,914

In [20]:
#Remove duplicate food items from Food_Item column and reset index
df1 = df1.drop_duplicates(subset=["Food_Item"], keep="first")
df1 = df1.reset_index(drop=True)
#Remove not needed columns
df1 = df1.drop(columns=["Sodium (mg)", "Meal_Type", "Date", "User_ID", "Water_Intake (ml)", "Cholesterol (mg)"])
#Rename fats column to Fats (g)
df1 = df1.rename(columns={"Fat (g)": "Fats (g)", "Fiber (g)": "Fibre (g)"})
df1

,Food_Item,Category,Calories (kcal),Protein (g),Carbohydrates (g),Fats (g),Fibre (g),Sugars (g)
0,Eggs,Meat,173,42.4,83.7,1.5,1.5,12.7
1,Apple,Fruits,66,39.2,13.8,3.2,2.6,12.2
2,Chicken Breast,Meat,226,27.1,79.1,25.8,3.2,44.7
3,Banana,Fruits,116,43.4,47.1,16.1,6.5,44.1
4,Oats,Grains,387,31.2,6.8,39.5,5.1,0.7
5,Carrot,Vegetables,138,28.2,12.4,20.2,2.8,37.8
6,Cookies,Snacks,69,36.8,17.8,15.0,9.6,36.4
7,Quinoa,Grains,204,19.3,62.7,31.8,6.8,40.3
8,Tomato,Vegetables,117,34.4,21.0,10.1,9.1,18.5
9,Orange Juice,Beverages,147,20.1,32.7,8.9,7.0,42.4
10,Beef Steak,Meat,157,27.5,32.4,9.4,0.5,24.6
11,Pork Chop,Meat,385,15.8,36.5,33.1,2.1,27.6
12,Grapes,Fruits,274,42.4,54.5,45.2,8.2,20.3
13,Milkshake,Beverages,353,24.0,96.2,6.8,0.9,17.5
14,Pasta,Grains,217,28.1,8.3,38.9,3.7,43.2
15,Orange,Fruits,222,21.1,85.0,45.1,1.7,46.8
16,Nuts,Snacks,552,25.9,27.4,39.2,1.5,47.3
17,Cheese,Dairy,252,18.0,24.9,31.0,8.2,43.6
18,Strawberry,Fruits,141,19.0,93.3,11.8,5.7,20.0
19,Butter,Dairy,315,37.8,25.5,15.6,1.2,1.0
20,Rice,Grains,142,14.6,21.9,41.4,2.7,46.5
21,Yogurt,Dairy,568,27.5,63.4,25.4,1.6,9.5
22,Broccoli,Vegetables,219,32.6,49.5,30.3,9.4,23.5
23,Water,Beverages,171,47.4,80.3,10.1,9.0,44.3
24,Paneer,Dairy,173,22.1,59.4,30.1,5.2,12.4
25,Salmon,Meat,508,5.3,70.4,40.3,6.1,47.2
26,Milk,Dairy,282,30.3,69.7,21.5,5.4,39.9
27,Coffee,Beverages,484,29.7,70.2,37.9,8.6,32.7
28,Spinach,Vegetables,282,12.0,54.0,6.6,2.2,29.4
29,Potato,Vegetables,161,30.4,72.8,31.4,7.3,38.4
30,Green Tea,Beverages,425,23.1,30.9,9.2,8.2,36.4
31,Bread,Grains,467,4.5,95.5,49.5,8.9,28.9
32,Chocolate,Snacks,153,46.7,91.0,45.0,7.0,49.7
33,Chips,Snacks,365,29.1,67.1,28.2,4.8,41.3
34,Popcorn,Snacks,481,38.6,36.8,12.2,8.1,22.2

In [21]:
df2=pd.read_csv('output_with_sugars.csv')
df2 = df2.drop_duplicates(subset=["Food"], keep="first")
#rename column names and keep them as in df1
df2 = df2.rename(columns={"Food": "Food_Item", "Fat": "Fats (g)", "Calories": "Calories (kcal)", "Group": "Category", "Protein": "Protein (g)", "Carbs": "Carbohydrates (g)", "Fiber": "Fibre (g)"})
#Remove not needed columns
df2 = df2.drop(columns=["Measure", "Grams", "Sat.Fat"])
df2

,Food_Item,Calories (kcal),Protein (g),Fats (g),Fibre (g),Carbohydrates (g),Category,Sugars (g)
0,Cows' milk,660,32,40,0.0,48.0,Dairy products,5.2
1,Milk skim,360,36,t,0.0,52.0,Dairy products,5.2
2,Buttermilk,127,9,5,0.0,13.0,Dairy products,5.2
3,"Evaporated, undiluted",345,16,20,0.0,24.0,Dairy products,4.8
4,Fortified milk,"1,373",89,42,1.4,119.0,Dairy products,5.2
...,...,...,...,...,...,...,...,...
330,Fruit-flavored soda,161,0,0,0.0,42.0,"Drinks,Alcohol, Beverages",10.6
331,Ginger ale,105,0,0,0.0,28.0,"Drinks,Alcohol, Beverages",8.0
332,Root beer,140,0,0,0.0,35.0,"Drinks,Alcohol, Beverages",8.0
333,Coffee,3,t,0,0.0,1.0,"Drinks,Alcohol, Beverages",0.0
334,Tea,4,0,t,0.0,1.0,"Drinks,Alcohol, Beverages",0.0

In [22]:
df4=pd.read_csv('cat.csv')
df4 = df4.drop_duplicates(subset=["Dish Name"], keep="first")
#Remove columns which are not in df1 and df2
df4 = df4.drop(columns=["Sodium (mg)","Calcium (mg)","Iron (mg)","Vitamin C (mg)","Folate (µg)"])
#Rename columns
df4 = df4.rename(columns={"Dish Name": "Food_Item", "Free Sugar (g)": "Sugars (g)"})
df4

,Food_Item,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Sugars (g),Fibre (g),Category
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,2.58,0.00,Beverages
1,Instant coffee,23.16,3.65,0.64,0.75,3.62,0.00,Beverages
2,Espreso coffee,51.54,6.62,1.75,2.14,6.53,0.00,Beverages
3,Iced tea,10.34,2.70,0.03,0.01,2.70,0.00,Beverages
4,Raw mango drink (Aam panna),35.92,9.05,0.16,0.03,7.49,0.61,Fruit
...,...,...,...,...,...,...,...,...
1009,Sweet and sour tomato pickle (Khatta meetha ta...,60.88,6.55,1.26,3.24,4.31,2.20,Vegetables
1010,Jhatpat achar with carrot (Jhatpat achaar gaja...,91.21,6.32,1.98,6.55,3.04,5.08,Vegetables
1011,Tomato chutney (Tamatar ki chutney),176.07,31.85,0.97,6.01,30.02,1.49,Vegetables
1012,Tomato ketchup,33.07,6.48,0.91,0.30,4.68,1.90,Vegetables
1013,Bengal 5 Spice Blend (Panch Phoran),289.79,20.00,18.26,22.16,1.40,18.40,Other

In [23]:
df5=pd.read_csv('3.csv')
df5 = df5.drop_duplicates(subset=["Food Name"], keep="first")
#Remove all omega & vitamin columns
df5 = df5.drop(columns=["Vitamin D","Vitamin E","Vitamin K","Omega-6 - Eicosadienoic acid","Omega-6 - Gamma-linoleic acid",
"Omega-3 - Eicosatrienoic acid","Omega-6 - Dihomo-gamma-linoleic acid","Omega-6 - Linoleic acid",
"Omega-6 - Arachidonic acid","Omega-3 - ALA","Copper","Manganese","Threonine","Tryptophan","Fructose","Folate","Iron", 
"Choline",	"Histidine",	"Isoleucine",	"Leucine",	"Lysine",	"Methionine",	"Phenylalanine", 
"Vitamin B12"	,"Vitamin B2"	,"Vitamin B3"	,"Vitamin B5"	,"Vitamin B6"	,"Vitamin C",
"Zinc"	,"Starch"	,"Valine", "Monounsaturated Fat", "Polyunsaturated fat", "Saturated Fat", "Omega-3 - EPA", "Phosphorus",	
"Potassium", "Net carbs",	"Omega-3 - DHA",	"Omega-3 - DPA", "Selenium",	"Sodium",	
"Trans Fat",	"Vitamin A (IU)",	"Vitamin A RAE",	"Vitamin B1", "Magnesium", "Calcium", "Cholesterol"])
#Rename columns
df5 = df5.rename(columns={"Food Name": "Food_Item","Category Name":"Category", "Calories": "Calories (kcal)", "Group": "Category", "Protein": "Protein (g)", "Carbs": "Carbohydrates (g)", "Fats": "Fats (g)","Sugar": "Sugars (g)", "Fiber": "Fibre (g)"})
df5

,Food_Item,Category,Calories (kcal),Carbohydrates (g),Fats (g),Fibre (g),Protein (g),Sugars (g)
0,Acerola,Fruits,32.0,7.7,0.30,1.1,0.40,NaN
1,Apple,Fruits,52.0,14.0,0.17,2.4,0.26,10.00
2,Apricot,Fruits,48.0,11.0,0.39,2.0,1.40,9.20
3,Dried fruit,Fruits,241.0,63.0,0.51,7.3,3.40,53.00
4,Avocado,Fruits,160.0,8.5,15.00,6.7,2.00,0.66
...,...,...,...,...,...,...,...,...
1169,Sesame chicken,"Meals, Entrees, and Side Dishes",293.0,27.0,14.00,0.7,14.00,16.00
1170,Vermicelli,"Meals, Entrees, and Side Dishes",331.0,82.0,0.10,3.9,0.10,17.00
1171,Baby food,Baby Foods,379.0,73.0,4.40,7.5,12.00,0.87
1172,Zwieback,Baby Foods,426.0,74.0,9.70,2.5,10.00,13.00
1173,Cherry juice,Baby Foods,47.0,11.0,0.10,0.3,0.20,11.00

In [24]:
#Concatenate all dataframes
name = pd.concat([df1, df2, df4, df5], axis=0, ignore_index=True)
food
#Remove duplicate rows & reset index
name = name.drop_duplicates(subset=["Food_Item"], keep="first")
name = food.reset_index(drop=True)
name

NameError: name 'food' is not defined

In [ ]:
#Save dataframe into csv
name.to_csv("output.csv", index=False)

In [ ]:
name["Category"].value_counts()

Category
Other                               281
Vegetables                          225
Meat                                142
Grains                              136
Baked Products                       99
Seafood                              92
Fruit                                89
Sweets                               88
Meals, Entrees, and Side Dishes      86
Dairy Products                       86
Beverages                            84
Fruits                               82
Prepared Dishes                      82
Soups                                70
Sweets & Desserts                    64
Dairy                                54
Greens                               53
Oils and Sauces                      48
Spices                               45
Breads, cereals, fastfood,grains     43
Pulses/Legumes                       40
Fast Foods                           40
Condiments                           36
Meat, Poultry                        30
Desserts, sweets                     27
Nuts                                 27
Vegetables R-Z                       27
Vegetables A-E                       27
Dairy products                       27
Fruits G-P                           26
Eggs                                 25
Fruits A-F                           21
Nuts/Seeds                           20
Fish, Seafood                        18
Vegetables F-P                       14
Seeds and Nuts                       12
Drinks,Alcohol, Beverages            11
Fats, Oils, Shortenings              11
Mushrooms                             8
Jams, Jellies                         8
Fruits R-Z                            8
Snacks                                5
Baby Foods                            3
Name: count, dtype: int64

In [ ]:
df6=pd.read_csv("food.csv")
#Remove column
df6 = df6.drop(columns=["Category_Original"])
df6

,Category,Food_Item,Calories (kcal),Protein (g),Carbohydrates (g),Fats (g),Fibre (g),Sugars (g)
0,Meat & Poultry,Eggs,173,42.4,83.7,1.5,1.5,12.70
1,Fruits,Apple,66,39.2,13.8,3.2,2.6,12.20
2,Meat & Poultry,Chicken Breast,226,27.1,79.1,25.8,3.2,44.70
3,Fruits,Banana,116,43.4,47.1,16.1,6.5,44.10
4,Grains & Breads,Oats,387,31.2,6.8,39.5,5.1,0.70
...,...,...,...,...,...,...,...,...
2415,Prepared Meals & Soups,Sesame chicken,293.0,14.0,27.0,14.0,0.7,16.00
2416,Prepared Meals & Soups,Vermicelli,331.0,0.1,82.0,0.1,3.9,17.00
2417,Baby Foods,Baby food,379.0,12.0,73.0,4.4,7.5,0.87
2418,Baby Foods,Zwieback,426.0,10.0,74.0,9.7,2.5,13.00
2419,Baby Foods,Cherry juice,47.0,0.2,11.0,0.1,0.3,11.00

In [ ]:
df6.to_csv("diet.csv", index=False)

In [ ]:
df7=pd.read_csv("diet_corrected.csv")

df7

,category,food,calories_kcal,protein_g,carbs_g,fat_g,fiber_g,sugar_g
0,Meat & Poultry,Eggs,173.0,30.0,83.7,2.0,1.5,12.7
1,Fruits,Apple,52.0,0.3,14.0,0.2,2.4,10.0
2,Meat & Poultry,Chicken Breast,226.0,27.1,79.1,20.0,3.2,44.7
3,Fruits,Banana,89.0,1.1,23.0,0.3,2.6,12.0
4,Grains & Breads,Oats,387.0,15.0,6.8,10.0,5.1,0.7
...,...,...,...,...,...,...,...,...
2442,Prepared Meals & Soups,Quinoa Salad,120.0,4.4,21.0,3.5,2.8,2.0
2443,Grains & Breads,Oatmeal (cooked),71.0,2.5,12.0,1.5,1.7,0.5
2444,Prepared Meals & Soups,Dosa (plain),168.0,3.9,30.0,3.7,1.5,1.0
2445,Prepared Meals & Soups,Upma,154.0,3.4,23.0,5.3,1.8,1.5
2446,Prepared Meals & Soups,Tuna Roll,132.0,6.0,23.0,2.6,1.0,2.0

In [ ]:
dfr=pd.read_csv("diet_clean.csv")
dfr = dfr.drop(columns=["category"])
dfr = dfr.rename(columns={"Category_original": "Category"})
dfr

,food,calories_kcal,protein_g,carbs_g,fat_g,fiber_g,sugar_g,protein_per_100kcal,Category
0,Eggs,173.0,25.93,72.34,1.73,1.5,12.7,14.9884,Meat & Poultry
1,Apple,52.0,0.30,14.00,0.20,2.4,10.0,0.5769,Fruits
2,Chicken Breast,226.0,21.47,0.00,15.85,0.0,0.0,9.5000,Meat & Poultry
3,Banana,89.0,1.10,23.00,0.30,2.6,12.0,1.2360,Fruits
4,Oats,387.0,15.00,6.80,10.00,5.1,0.7,3.8760,Grains & Breads
...,...,...,...,...,...,...,...,...,...
2402,Quinoa Salad,120.0,4.40,21.00,3.50,2.8,2.0,3.6667,Prepared Meals & Soups
2403,Oatmeal (cooked),71.0,2.50,12.00,1.50,1.7,0.5,3.5211,Grains & Breads
2404,Dosa (plain),168.0,3.90,30.00,3.70,1.5,1.0,2.3214,Prepared Meals & Soups
2405,Upma,154.0,3.40,23.00,5.30,1.8,1.5,2.2078,Prepared Meals & Soups
2406,Tuna Roll,132.0,6.00,23.00,2.60,1.0,2.0,4.5455,Prepared Meals & Soups

In [ ]:
dfr.to_csv("Final.csv", index=False)